theme: jekyll-theme-slate
<div class="x-column x-sm x-1-3" style="padding: 0px 20px; color:white; opacity: 100;"><span><h2 class="x-feature-box-title">
Get Involved</h2></span><hr class="x-gap" style="margin: 10px 0 0 0;"><div class="x-text"><p class="x-feature-box-text">Nothing
greater than giving back to the society. <a href="Get Involved.html" title="Learn More" style="color: #1e73be;">Learn More</a></p></div></div></div></div></div>
<div class="x-column x-sm x-1-3" style="padding: 0px 20px; color:white; opacity: 100";><span><h2>Donate a Blanket, Save a Life</h2></span></h2><hr class="x-gap" style="margin: 10px 0 0 0;"><div class="x-text"><p>There is no better gift than providing warm clothing to the needy during winter season. Lakhs of homeless experience bitterness of winter and are at a great risk of suffering from severe illnesses.</p>
<p> The rise in air pollution levels and the early onset of winter this year have made them vulnerable, but at the same time it has given us an opportunity to serve humanity by donating blankets to the needy. </p>
<p>This winter, become a part of our mission. There cannot be a bigger satisfaction than saving someone’s life. </p>
<h2 class="h-custom-headline h3" style="color:white; opacity: 100;"><span>Feed the Hungry Mouths. </span></h2><hr class="x-gap" style="margin: 10px 0 0 0;"><div class="x-text"><p><em>Your small contribution will support us to feed family members &#038; caregivers of underprivileged patients in the hospital</em></p>
<p>Majority of the underprivileged patients admitted in Government hospitals are those who come from nearby states are often poor, in several cases family members decide to stay hungry to save money.</p>
<p>Uday Foundation serve free, but wholesome, food to families of underprivileged patients in the Govt. Hospital and also for the children who come from a far-off places to the Delhi hospitals for often longer treatments. </p>
</div>
  </div>
</div></div>
<div class="x-column x-sm x-1-3" style="padding: 0px 20px; color:white; opacity: 100;"<span><h2 class="x-feature-box-title"><div class="x-column x-md x-1-3"><div id="text-65" class="widget widget_text">Contact Us</h2> <hr class="x-gap" style="margin: 10px 0 0 0;"><div class="x-text"><div class="textwidget"><p>     New Life Foundation, 113A/1, Singanallur, Coimbatore- 641014, Tamil Nadu. <br/>
<p>Email: newlifefoundation@gmail.com , Phone: +91-11-26561444</strong></p>
</div>
</div>
<script>
window.onscroll = function() {myFunction()};
var header = document.getElementById("myHeader");
var sticky = header.offsetTop;
function myFunction() {
  if (window.pageYOffset > sticky) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}
</script>
<script>
var slideIndex = 0;
showSlides();
function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";  
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}    
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

</body>
</html>
